# Generated by Django 4.2.14 on 2024-07-20 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmapp', '0002_processeddata_delete_uploadedfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processeddata',
            options={'verbose_name': 'Output Data', 'verbose_name_plural': "Output Data's"},
        ),
    ]
